name: digital-employee-middleware
services:
  middleware_postgres:
    build:
      context: db
      dockerfile: Dockerfile
    container_name: postgres-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - middleware_postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_preload_libraries=vector
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U digital_employee" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      digital-employee-network:
        aliases:
          - db

volumes:
  middleware_postgres_data:

networks:
  digital-employee-network:
    driver: bridge